### ISSUE TITLE
Initiate the documents - main.nf nextflow.config, gadi.config , README.md

### ISSUE THREAD

**Issue by nandan75** [Sydney-Informatics-Hub/RNAseq-DE-nf#9]
- Check , add  contents which make the core main.nf for this project using default template 
- Check , add  contents which make the core nextflow.config, gadi.config files for this project using default template 
- Add details to Readme.md using information from [RNASeq-DE](https://github.com/Sydney-Informatics-Hub/RNASeq-DE/tree/Nandan_checks_May23).
   - We can keep adding to this as we progress

**Comment by georgiesamaha** [comment]
For readme, please follow this template https://github.com/AustralianBioCommons/doc_guidelines/blob/master/documentation_templates/workflows.md
